name: sandeepdhillon
favicon: null
layout_spectrum: 0.152580248657614
typography_spectrum: 0.18127688230015337
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.46991468383930624
  lightness: 0.7099082085769624
  saturation: 0.13193558412604034
  rhythmicContrast: 0.9089689773973078
purpose: []
